global abbreviations
abbreviations = {
    0: "", # Ones
    3: "K", # Thousand
    6: "M", # Million
    9: "B", # Billion
    12: "T", # Trillion
    15: "Qd", # Quadrillion
    18: "Qn", # Quintillion
    21: "Sx", # Sextillion
    24: "Sp", # Septillion
    27: "Oc", # Octillion
    30: "No", # Nonillion
    33: "Dc", # Decillion
    36: "UDc", # Undecillion
    39: "DDc", # Duodecillion
    42: "TDc", # Tredecillion
    45: "QdD", # Quattuordecillion
    48: "QnD", # Quindecillion
    51: "SxD", # Sexdecillion
    54: "SpD", # Septendecillion
    57: "OcD", # Octodecillion
    60: "NoD", # Novemdecillion
    63: "Vg", # Vigintillion
    66: "UVg", # Unvigintillion
    69: "DVg", # Duovigintillion
    72: "TVg", # Trevigintillion
    75: "QdV", # Quattuorvigintillion
    78: "QnV", # Quinvigintillion
    81: "SxV", # Sexvigintillion
    84: "SpV", # Septenvigintillion
    87: "OcV", # Octovigintillion
    90: "NoV", # Novemvigintillion
    93: "Tg", # Trigintillion
    96: "UTg", # Untrigintillion
    99: "DTg", # Duotrigintillion
    102: "TTg", # Tretrigintillion
    105: "QdT", # Quattuortrigintillion
    108: "QnT", # Quintrigintillion
    111: "SxT", # Sextrigintillion
    114: "SpT", # Septentrigintillion
    117: "OcT", # Octotrigintillion
    120: "NoT", # Novemtrigintillion
    123: "Qa", # Quadragintillion
    126: "UQa", # Unquadragintillion
    129: "DQa", # Duoquadragintillion
    132: "TQa", # Trequadragintillion
    135: "QdQa", # Quattuorquadragintillion
    138: "QnQa", # Quinquadragintillion
    141: "SxQa", # Sexquadragintillion
    144: "SpQa", # Septenquadragintillion
    147: "OcQa", # Octoquadragintillion
    150: "NoQa", # Novemquadragintillion
    153: "Qi", # Quinquagintillion
    156: "UQi", # Unquinquagintillion
    159: "DQi", # Duoquinquagintillion
    162: "TQi", # Trequinquagintillion
    165: "QdQi", # Quattuorquinquagintillion
    168: "QnQi", # Quinquinquagintillion
    171: "SxQi", # Sexquinquagintillion
    174: "SpQi", # Septenquinquagintillion
    177: "OcQi", # Octoquinquagintillion
    180: "NoQi", # Novemquinquagintillion
    183: "Se", # Sexagintillion
    186: "USe", # Unsexagintillion
    189: "DSe", # Duosexagintillion
    192: "TSe", # Tresexagintillion
    195: "QdSe", # Quattuorsexagintillion
    198: "QnSe", # Quinsexagintillion
    201: "SxSe", # Sexsexagintillion
    204: "SpSe", # Septensexagintillion
    207: "OcSe", # Octosexagintillion
    210: "NoSe", # Novemsexagintillion
    213: "St", # Septuagintillion
    216: "USt", # Unseptuagintillion
    219: "DSt", # Duoseptuagintillion
    222: "TSt", # Treseptuagintillion
    225: "QdSt", # Quattuorseptuagintillion
    228: "QnSt", # Quinseptuagintillion
    231: "SxSt", # Sexseptuagintillion
    234: "SpSt", # Septenseptuagintillion
    237: "OcSt", # Octoseptuagintillion
    240: "NoSt", # Novemseptuagintillion
    243: "Og", # Octogintillion
    246: "UOg", # Unoctogintillion
    249: "DOg", # Duooctogintillion
    252: "TOg", # Treoctogintillion
    255: "QdOg", # Quattuoroctogintillion
    258: "QnOg", # Quinoctogintillion
    261: "SxOg", # Sexoctogintillion
    264: "SpOg", # Septenoctogintillion
    267: "OcOg", # Octooctogintillion
    270: "NoOg", # Novemoctogintillion
    273: "Nn", # Nonagintillion
    276: "UNn", # Unnonagintillion
    279: "DNn", # Duononagintillion
    282: "TNn", # Trenonagintillion
    285: "QdNn", # Quattuornonagintillion
    288: "QnNn", # Quinnonagintillion
    291: "SxNn", # Sexnonagintillion
    294: "SpNn", # Septennonagintillion
    297: "OcNn", # Octononagintillion
    300: "NoNn", # Novemnonagintillion
    303: "C", # Centillion
    306: "UC", # Uncentillion
    309: "DC", # Duocentillion
    312: "TC", # Trecentillion
    315: "QdC", # Quattuorcentillion
    318: "QnC", # Quincentillion
    321: "SxC", # Sexcentillion
    324: "SpC", # Septencentillion
    327: "OcC", # Octocentillion
    330: "NoC", # Novemcentillion
    333: "D", # Decicentillion
    336: "UD", # Undecicentillion
    339: "DD", # Duodecicentillion
    342: "TD", # Tredecicentillion
    345: "QdD", # Quattuordecicentillion
    348: "QnD", # Quindecicentillion
    351: "SxD", # Sexdecicentillion
    354: "SpD", # Septendecicentillion
    357: "OcD", # Octodecicentillion
    360: "NoD", # Novemdecicentillion
    363: "Vg", # Viginticentillion
    366: "UVg", # Unviginticentillion
    369: "DVg", # Duoviginticentillion
    372: "TVg", # Treviginticentillion
    375: "QdV", # Quattuorviginticentillion
    378: "QnV", # Quinviginticentillion
    381: "SxV", # Sexviginticentillion
    384: "SpV", # Septenviginticentillion
    387: "OcV", # Octoviginticentillion
    390: "NoV", # Novemviginticentillion
    393: "Tg", # Trigintacentillion
    396: "UTg", # Untrigintacentillion
    399: "DTg", # Duotrigintacentillion
    402: "TTg", # Tretrigintacentillion
    405: "QdT", # Quattuortrigintacentillion
    408: "QnT", # Quintrigintacentillion
    411: "SxT", # Sextrigintacentillion
    414: "SpT", # Septentrigintacentillion
    417: "OcT", # Octotrigintacentillion
    420: "NoT", # Novemtrigintacentillion
    423: "Qa", # Quadragintacentillion
    426: "UQa", # Unquadragintacentillion
    429: "DQa", # Duoquadragintacentillion
    432: "TQa", # Trequadragintacentillion
    435: "QdQa", # Quattuorquadragintacentillion
    438: "QnQa", # Quinquadragintacentillion
    441: "SxQa", # Sexquadragintacentillion
    444: "SpQa", # Septenquadragintacentillion
    447: "OcQa", # Octoquadragintacentillion
    450: "NoQa", # Novemquadragintacentillion
    453: "Qi", # Quinquagintacentillion
    456: "UQi", # Unquinquagintacentillion
    459: "DQi", # Duoquinquagintacentillion
    462: "TQi", # Trequinquagintacentillion
    465: "QdQi", # Quattuorquinquagintacentillion
    468: "QnQi", # Quinquinquagintacentillion
    471: "SxQi", # Sexquinquagintacentillion
    474: "SpQi", # Septenquinquagintacentillion
    477: "OcQi", # Octoquinquagintacentillion
    480: "NoQi", # Novemquinquagintacentillion
    483: "Se", # Sexagintacentillion
    486: "USe", # Unsexagintacentillion
    489: "DSe", # Duosexagintacentillion
    492: "TSe", # Tresexagintacentillion
    495: "QdSe", # Quattuorsexagintacentillion
    498: "QnSe", # Quinsexagintacentillion
    501: "SxSe", # Sexsexagintacentillion
    504: "SpSe", # Septensexagintacentillion
    507: "OcSe", # Octosexagintacentillion
    510: "NoSe", # Novemsexagintacentillion
    513: "St", # Septuagintacentillion
    516: "USt", # Unseptuagintacentillion
    519: "DSt", # Duoseptuagintacentillion
    522: "TSt", # Treseptuagintacentillion
    525: "QdSt", # Quattuorseptuagintacentillion
    528: "QnSt", # Quinseptuagintacentillion
    531: "SxSt", # Sexseptuagintacentillion
    534: "SpSt", # Septenseptuagintacentillion
    537: "OcSt", # Octoseptuagintacentillion
    540: "NoSt", # Novemseptuagintacentillion
    543: "Og", # Octogintacentillion
    546: "UOg", # Unoctogintacentillion
    549: "DOg", # Duooctogintacentillion
    552: "TOg", # Treoctogintacentillion
    555: "QdOg", # Quattuoroctogintacentillion
    558: "QnOg", # Quinoctogintacentillion
    561: "SxOg", # Sexoctogintacentillion
    564: "SpOg", # Septenoctogintacentillion
    567: "OcOg", # Octooctogintacentillion
    570: "NoOg", # Novemoctogintacentillion
    573: "Nn", # Nonagintacentillion
    576: "UNn", # Unnonagintacentillion
    579: "DNn", # Duononagintacentillion
    582: "TNn", # Trenonagintacentillion
    585: "QdNn", # Quattuornonagintacentillion
    588: "QnNn", # Quinnonagintacentillion
    591: "SxNn", # Sexnonagintacentillion
    594: "SpNn", # Septennonagintacentillion
    597: "OcNn", # Octononagintacentillion
    600: "NoNn", # Novemnonagintacentillion
    603: "C", # Ducentillion
} # Please note that all the Centillion numbers and onwards dont have correct notation - https://en.wikipedia.org/wiki/Names_of_large_numbers#Extensions_of_the_standard_dictionary_numbers
